# Based on Flutter config: https://github.com/flutter/flutter/blob/master/.gemini/config.yaml
#
# Schema: https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github#config.yaml-schema

# No poetry in summaries (DEFAULT).
have_fun: false

code_review:
  # (DEFAULT)
  disable: false
  # LOW, MEDIUM, HIGH or CRITICAL
  comment_severity_threshold: MEDIUM
  # -1 is unlimited (DEFAULT)
  max_review_comments: -1
  pull_request_opened:
    # (DEFAULT)
    help: false
    summary: false
    code_review: true
    # (DEFAULT) -- Note that this is disabled for flutter
    include_drafts: true
ignore_patterns:
  - "third_party/build/**"
  - "third_party/bin/**"
  - "dart-sdk/**"
  - ".idea/**"
  - "third_party/.idea/**"
  - "third_party/.settings/**"
  - "third_party/.gradle/**"
  - "third_party/.intellijPlatform/**"
  - "third_party/.kotlin/**"
  - "third_party/gradle/wrapper/gradle-wrapper.jar"
  - "third_party/tool/baseline/**"
  - "tool/.dart_tool/**"
